---
title: "Ectrics2CA5"
author: "Ties van der Veen"
date: "6-3-2020"
output: pdf_document
---

## Rebecca Costello, Ties van der Veen, Matei van der Meer

# II. What to submit

**Theory**

(a)

The treatment described in the paper is an increase in police patrols on preselected crime hot spots (street segments).

(b)

For their findings, the authors mention a number of mechanics that could explain the results. First, they find a large decrease in reported car thefts in targeted streets yet no drop in the other monitored criminal activity. This could be due to context-specific characteristics of the criminals & police.

Second, they note an increase in security perceptions. This is directly related to the increase in patrols, however it is also bound by it. After the experiment, patrols returned to their original level and so did security perceptions.

Third, they find a large drop in car thefts in hot spots close to targeted streets. This points to spillover effects. 

Fourth, they look at heterogenous treatment effects. They find that the effects in the least secure hotspots are much larger than those closer to the base level. 

Lastly, a comparison of average effects is conducted. The authors note that there is a (non-significant, yet likely) decrease in car thefts due to the treatment. 

(c)

As they referred to in the first point of (b), and further on in the paper, the effects of hot spot policing work differently for different countries. The US has a lot of research on this topic already, but the authors found different results for Medellín. A lot of comparisons were made with Blattman et al. (2018) who conducted their research in Bogotá, and while they found some similar effects, some were also only found in Medellín.

**Strength of evidence**

(d)

Due to the use of the non-experimental streets, there is decent statistical power for the spillover effects. However, due to non-significance of the single main effect (reduction in car thefts) and its lower statistical power (as this was not a spillover), I don't think action should be taken purely for this effect. If further research could clarify these effects this could be revised.

**Economics of scaling**

(e)

The authors refer to Blattman et al. (2018) to identify scaling issues. First, they look at the stable unit treatment value assumption and its possible violation due to crime displacement or control streets receiving less or more policing. They account for this by dividing the control streets into categories depending on distance to treated hotspots. 

Second, they describe the issue of fuzzy clustering (multiple hotspots close near eachother, one being assigned as a hotspot and the rest becoming spillovers). To combat this, they use randomization inference to estimate the p-values. The randomization procedure is repeated 1000 times, and from each the treatment and spillover effects are measured. Then the p-value is estimated in each case as the probability of obtaining an estimate that is as large as the one generated by the experiment.

Last, the restrictions imposed by the Metropolitan Police are mentioned. For this, each observation is weighted by the inverse of the probability of being exposed to its experimental condition.  In other words, streets that had high probability to being assigned to a condition got weighted less. 

Costs and benefits of scaling up the treatment are not discussed.

(f)

As mentioned in (e), spillovers are managed by using randomization inference. They find that there are no spillover effects to other types of crimes (only property/car theft). Due to the large amount of non-experimental streets however, relatively small spillovers could still have an effect. 
